import { StyleSheet, Platform } from 'react-native';
import { colors, typography, spacing, buttonSizes, inputSizes, shadows, radius } from '../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.secondary,
  },
  content: {
    flexGrow: 1,
    paddingBottom: 100,
  },
  headerContainer: {
    backgroundColor: colors.primary,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.xl,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  welcomeText: {
    ...typography.h2,
    color: colors.text.white,
  },
  logoutButton: {
    ...buttonSizes.small,
    backgroundColor: colors.primaryLight,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutText: {
    ...typography.buttonSmall,
    color: colors.text.white,
  },
  title: {
    ...typography.h1,
    color: colors.text.white,
    marginTop: spacing.sm,
  },
  subtitle: {
    ...typography.body,
    color: colors.primaryLight,
    marginTop: spacing.xs,
  },
  quickRoutesContainer: {
    marginBottom: spacing.lg,
    padding: spacing.md,
    backgroundColor: colors.background.primary,
    borderRadius: radius.md,
  },
  quickRoutesLabel: {
    ...typography.bodyBold,
    color: colors.text.primary,
    marginBottom: spacing.sm,
  },
  quickRoutesButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  quickRouteButton: {
    backgroundColor: colors.primaryLight,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.lg,
    margin: spacing.xs / 2,
  },
  quickRouteText: {
    ...typography.caption,
    color: colors.text.white,
    fontWeight: '500',
  },
  formContainer: {
    flex: 1,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
  },
  tripTypeContainer: {
    flexDirection: 'row',
    marginBottom: spacing.xl,
    backgroundColor: colors.background.card,
    borderRadius: radius.lg,
    padding: 4,
    shadowColor: colors.shadow.light,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 4,
  },
  tripTypeButton: {
    flex: 1,
    ...buttonSizes.medium,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
  },
  tripTypeButtonActive: {
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  tripTypeText: {
    ...typography.button,
    color: colors.text.secondary,
  },
  tripTypeTextActive: {
    ...typography.button,
    color: colors.text.white,
  },
  locationCard: {
    backgroundColor: colors.background.card,
    borderRadius: radius.lg,
    marginBottom: spacing.lg,
    shadowColor: colors.shadow.light,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 4,
  },
  locationContainer: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    gap: 8,
  },
  swapButtonContainer: {
    position: 'absolute',
    right: 16,
    top: '50%',
    transform: [{ translateY: -20 }],
    zIndex: 2,
  },
  swapButton: {
    width: 40,
    height: 40,
    backgroundColor: colors.primary,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  swapButtonText: {
    ...typography.h4,
    color: colors.text.white,
  },
  dateCard: {
    backgroundColor: colors.background.card,
    borderRadius: radius.lg,
    marginBottom: spacing.lg,
    shadowColor: colors.shadow.light,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 4,
  },
  dateContainer: {
    flexDirection: 'row',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
  },
  dateButton: {
    flex: 1,
    paddingVertical: spacing.md,
    alignItems: 'center',
  },
  dateButtonActive: {
    backgroundColor: colors.background.tertiary,
    borderRadius: radius.md,
    marginHorizontal: spacing.xs,
    paddingVertical: spacing.lg,
  },
  dateLabel: {
    ...typography.captionMedium,
    color: colors.text.secondary,
    marginBottom: spacing.xs,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dateText: {
    ...typography.bodySemiBold,
    color: colors.text.primary,
  },
  dateDivider: {
    width: 1,
    backgroundColor: colors.border.light,
    marginHorizontal: spacing.md,
  },
  optionsCard: {
    backgroundColor: colors.background.card,
    borderRadius: radius.lg,
    marginBottom: spacing.xl,
    shadowColor: colors.shadow.light,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 4,
  },
  optionsContainer: {
    flexDirection: 'row',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
  },
  passengersContainer: {
    flex: 1,
    marginRight: spacing.md,
  },
  classContainer: {
    flex: 1,
    marginLeft: spacing.md,
  },
  optionLabel: {
    ...typography.captionMedium,
    color: colors.text.secondary,
    marginBottom: spacing.md,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  counterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.background.tertiary,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  counterButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterButtonDisabled: {
    backgroundColor: colors.text.muted,
  },
  counterButtonText: {
    ...typography.bodySemiBold,
    color: colors.text.white,
    fontSize: 18,
  },
  counterText: {
    ...typography.bodySemiBold,
    color: colors.text.primary,
  },
  classButton: {
    backgroundColor: colors.background.tertiary,
    borderRadius: radius.md,
    paddingVertical: spacing.md,
    alignItems: 'center',
  },
  classText: {
    ...typography.bodySemiBold,
    color: colors.text.primary,
  },
  searchButton: {
    ...buttonSizes.extraLarge,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 40 : 20,
    left: spacing.xl,
    right: spacing.xl,
    zIndex: 10,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  searchButtonDisabled: {
    backgroundColor: colors.text.muted,
    shadowOpacity: 0.1,
  },
  searchButtonText: {
    ...typography.button,
    color: colors.text.white,
    fontSize: 18,
  },
});