export const strings = {
  navigation: {
    flightSearchTitle: 'Flight Search',
    flightResultsTitle: 'Flight Results',
    flightDetailsTitle: 'Flight Details',
  },

  auth: {
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Sign in to search and book flights',
    createAccount: 'Create Account',
    registerSubtitle: 'Join us to discover amazing flights',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    login: 'Sign In',
    register: 'Sign Up',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    signingIn: 'Signing In...',
    creatingAccount: 'Creating Account...',
    forgotPassword: 'Forgot Password',
    noAccount: 'Don\'t have an account?',
    haveAccount: 'Already have an account?',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    or: 'or',
    usernamePlaceholder: 'Enter username',
    passwordPlaceholder: '••••••••',
    registerSuccess: 'Registration Successful!',
    registerSuccessMessage: 'Your account has been created successfully. You can now sign in with your credentials.',
  },

  flightSearch: {
    title: 'Search Flights',
    subtitle: 'Find the best flight deals',
    hello: 'Hello',
    oneWay: 'One Way',
    roundTrip: 'Round Trip',
    from: 'From',
    to: 'To',
    fromPlaceholder: 'From (e.g., Istanbul)',
    toPlaceholder: 'To (e.g., London)',
    departure: 'Departure',
    return: 'Return',
    selectDate: 'Select Date',
    passengers: 'Passengers',
    class: 'Class',
    economy: 'Economy',
    business: 'Business',
    firstClass: 'First Class',
    search: 'Search Flights',
    searching: 'Searching Flights...',
  },

  flightResults: {
    flightsFound: 'flights found',
    route: 'Istanbul → London',
    date: 'Feb 15',
    searchingFlights: 'Searching for flight options...',
    filters: {
      best: 'Best',
      cheapest: 'Cheapest',
      fastest: 'Fastest',
    },
    perPerson: 'per person',
    direct: 'Direct',
    oneStop: '1 Stop',
    multipleStops: 'Stops',
    tags: {
      bestValue: 'Best Value',
      cheapest: 'Cheapest',
      fastest: 'Fastest',
    },
    noResults: {
      title: 'No flights found for selected dates',
      message: 'Try different dates or check nearby airports.',
      newSearchButton: 'New Search',
    },
    loadFailed: 'Failed to load flight results',
  },

  common: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    ok: 'OK',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    retry: 'Retry',
  },

  errors: {
    required: 'This field is required',
    invalidUsername: 'Please enter a valid username',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    usernameTooShort: 'Username must be at least 3 characters',
    missingFields: 'Please fill in all fields',
    loginFailed: 'Login Failed',
    registerFailed: 'Registration Failed',
    searchFailed: 'Search Failed',
    logoutFailed: 'Failed to logout',
    unknownError: 'Unknown error',
    missingOriginDestination: 'Please enter origin and destination',
    flightSearchFailed: 'Unable to search flights. Please try again.',
    networkError: 'Please check your internet connection',
    usernameExists: 'Username already exists',
    invalidCredentials: 'Invalid username or password',
  },

  connectivity: {
    noConnection: 'No Internet Connection',
  },
  ui: {
    closeButton: '×',
    warningIcon: '⚠️',
  },
  logs: {
    networkConnectivityChanged: 'Network connectivity changed',
  },
};
